version: '3'
services:
  apache:
    build: .docker/apache
    container_name: dichipot_apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/dichipot
    depends_on:
      - php

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: dichipot_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4

  php:
    build: .docker/php
    container_name: dichipot_php
    volumes:
      - .:/home/wwwroot/dichipot
    environment:
      - maildev_host=dichipot_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dichipot_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: dichipot_maildev
    ports:
      - 8001:80
