version: '3'
services:
  apache:
    image: 257776165751.dkr.ecr.eu-west-3.amazonaws.com/prod/dichipot_apache:latest
    container_name: dichipot_apache
    ports:
      - 80:80
    depends_on:
      - php

  mysql:
    image: mysql
    container_name: dichipot_mysql
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4

  php:
    image: 257776165751.dkr.ecr.eu-west-3.amazonaws.com/prod/dichipot_php:latest
    container_name: dichipot_php
    environment:
      - maildev_host=dichipot_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dichipot_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: dichipot_maildev
    ports:
      - 8001:80

volumes:
  db:
    driver: local
